# Generated by Django 4.1.1 on 2022-09-13 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256)),
                ('last_name', models.CharField(max_length=256)),
                ('birthday', models.DateField()),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='img')),
                ('phone_number', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('city', models.CharField(max_length=256)),
            ],
        ),
    ]
